### ISSUE TITLE
500 error after saving Importer as a module to that project

### ISSUE THREAD

**Issue by mysen** [leovitch/redmine_importer#28]
Redmine version                          2.0.0.devel

Started GET "/projects/abc/settings/modules" for 183.1.204.95 at 2012-05-24 10:55:12 +0000
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"abc", "tab"=>"modules"}
  Rendered projects/_form.html.erb (17.0ms)
  Rendered projects/_edit.html.erb (18.7ms)
  Rendered projects/settings/_modules.html.erb (3.6ms)
  Rendered projects/settings/_members.html.erb (11.7ms)
  Rendered projects/settings/_versions.html.erb (2.7ms)
  Rendered projects/settings/_issue_categories.html.erb (1.1ms)
  Rendered projects/settings/_wiki.html.erb (1.7ms)
  Rendered projects/settings/_activities.html.erb (79.7ms)
  Rendered common/_tabs.html.erb (124.4ms)
  Rendered projects/settings.html.erb within layouts/base (125.1ms)
Completed 500 Internal Server Error in 172ms

ActionController::RoutingError (No route matches {:project_id=>#<Project id:1234, name: "ABC", description: "ABC China", homepage: "", is_public: false, parent_id: nil, created_on: "2012-05-24 09:57:30", updated_on: "2012-05-24 09:57:30", identifier: "abc", status: 1, lft: 191, rgt: 220>, :controller=>"importer"}):
  lib/redmine/menu_manager.rb:150:in `render_single_menu_node'
  lib/redmine/menu_manager.rb:102:in`render_menu_node'
  lib/redmine/menu_manager.rb:91:in `block in render_menu'
  lib/redmine/menu_manager.rb:168:in`block in menu_items_for'
  lib/redmine/menu_manager.rb:165:in `each'
  lib/redmine/menu_manager.rb:165:in`menu_items_for'
  lib/redmine/menu_manager.rb:90:in `render_menu'
  lib/redmine/menu_manager.rb:80:in`render_main_menu'
  app/views/layouts/base.html.erb:51:in `_app_views_layouts_base_html_erb___657420175069464130_23414940'

**Comment by mikewolfli** [comment]
Hello All, I met the same error, who can give a solution?

**Comment by mysen** [comment]
Hi mike, it's auto-resolved in 2.0 stable version, I'm gonna close this out. Please check out:
http://www.redmine.org/projects/redmine/wiki/Download#20-Stable

**Comment by TomBodet** [comment]
Wish this wasn't closed as I'm running 2.0.3 on an RVM/Passenger stack on Cent6.2 64bit.  Bundle includes:
- actionmailer (3.2.6)
  - actionpack (3.2.6)
  - activemodel (3.2.6)
  - activerecord (3.2.6)
  - activeresource (3.2.6)
  - activesupport (3.2.6)
  - arel (3.0.2)
  - builder (3.0.0)
  - bundler (1.1.3)
  - coderay (1.0.7)
  - erubis (2.7.0)
  - fastercsv (1.5.5)
  - hike (1.2.1)
  - i18n (0.6.0)
  - journey (1.0.4)
  - json (1.7.4)
  - mail (2.4.4)
  - mime-types (1.19)
  - multi_json (1.3.6)
  - mysql2 (0.3.11)
  - net-ldap (0.3.1)
  - polyglot (0.3.3)
  - prototype-rails (3.2.1)
  - rack (1.4.1)
  - rack-cache (1.2)
  - rack-openid (1.3.1)
  - rack-ssl (1.3.2)
  - rack-test (0.6.1)
  - rails (3.2.6)
  - railties (3.2.6)
  - rake (0.9.2.2)
  - rdoc (3.12)
  - rmagick (2.13.1)
  - ruby-openid (2.1.8)
  - sprockets (2.1.3)
  - sqlite3 (1.3.6)
  - thor (0.15.4)
  - tilt (1.3.3)
  - treetop (1.4.10)
  - tzinfo (0.3.33)
  - yard (0.8.2.1)

I'm getting this exact same issue.  Everything appears to be working until I actually enable the import module for a project.  Then that projects page gets hosed and I can't get to it unless I remove the plugin.  Only message I see is in the developer.log:
Repository Load (0.8ms)  SELECT `repositories`.\* FROM `repositories` WHERE `repositories`.`project_id` = 33 AND (is_default = 1) LIMIT 1
Completed 500 Internal Server Error in 146ms

ActionController::RoutingError (No route matches {:project_id=>#<Project id: 33, name: "Test Proj 1", description: "just messin", homepage: "", is_public: true, parent_id: nil, created_on: "2012-06-26 15:23:51", updated_on: "2012-06-26 15:23:51", identifier: "testprojkpr1", status: 1, lft: 53, rgt: 54>, :controller=>"importer"}):
  lib/redmine/menu_manager.rb:150:in `render_single_menu_node'
  lib/redmine/menu_manager.rb:102:in`render_menu_node'
  lib/redmine/menu_manager.rb:91:in `block in render_menu'
  lib/redmine/menu_manager.rb:168:in`block in menu_items_for'
  lib/redmine/menu_manager.rb:165:in `each'
  lib/redmine/menu_manager.rb:165:in`menu_items_for'
  lib/redmine/menu_manager.rb:90:in `render_menu'
  lib/redmine/menu_manager.rb:80:in`render_main_menu'
  app/views/layouts/base.html.erb:51:in `_app_views_layouts_base_html_erb__2794649929935224358_22380740'
  app/controllers/projects_controller.rb:168:in`show'

**Comment by Glideh** [comment]
Same error here on redmine 2.0.3 Ubuntu 12.10.
I had to disable the module form the db while no solution for this problem.

``` SQL
DELETE FROM enabled_modules WHERE project_id = <my_project>, name = 'importer';
```

Is there any solution yet ?

**Comment by brunosimioni** [comment]
same problem over here. redmine 2.2.3.
