### ISSUE TITLE
Around auto-adding fixed_versions, categories fails...

### ISSUE THREAD

**Issue by mschibata** [leovitch/redmine_importer#7]
Hello,

Categories and Fixed versions are defined for each projects.

Following changes may be necessary.

app\controllers\importer_controller.rb

174  -      category = IssueCategory.find_by_name(category_name)
     +      category = IssueCategory.find_by_project_id_and_name(project.id, category_name)

181 -      fixed_version = Version.find_by_name(fixed_version_name)
     +      fixed_version = Version.find_by_project_id_and_name(project.id, fixed_version_name)

Regards,

**Comment by leovitch** [comment]
Good catch.  Incorporated proposed changes.
