### ISSUE TITLE
Custom User Field not importing

### ISSUE THREAD

**Issue by jimtaylor3** [leovitch/redmine_importer#8]
I created a custome field 'Owner' with format 'user' - with checkbox checked for  'Required', 'For all projects', and 'Used as filter'.

When I import from a file I created from a csv of data from another system, everything but the Owner field is imported.

Column headings on my file are:   

'Category', 'ERP CTL XRF', 'Subject', 'description', 'status', 'est (days)', 'Estimated Hours', 'Assignee', 'owner'
- ERP CTL XRF - is a custom field - format 'text' no limit, not required, check box for 'Used as filter' is checked.
- est (days) is ignored

I have tried both the sign-in id format for owner - flastname  as well as the format specified for users in my set up 'Firstname Lastname' 

I also tried adding a column after owner - Tracker, with Task in each row.  No difference.

**Comment by kimus** [comment]
There is also a problem importing dates to a Custom fields with type Date

**Comment by leovitch** [comment]
It's true, the non-string formats all needed a little bit of special support in the Importer.  I've added all types except "list".

Current HEAD has been updated with this support as well as some performance and error-reporting improvements.  Sorry it took so long.
